-- Raw_Card Table Definition
-- Generated from JHBI Data Catalog

CREATE TABLE raw_card (
    card_transaction_id VARCHAR(255) NOT NULL COMMENT 'Unique card transaction identifier',
    authorization_code VARCHAR(255) NULL COMMENT 'Authorization approval code',
    retrieval_reference_number VARCHAR(255) NULL COMMENT 'Acquirer reference number (ARN)',
    card_type VARCHAR(255) NOT NULL COMMENT 'CREDIT, DEBIT, PREPAID, GIFT',
    card_brand VARCHAR(255) NOT NULL COMMENT 'Card network brand',
    card_number_token VARCHAR(255) NOT NULL COMMENT 'Tokenized PAN',
    card_last_four VARCHAR(255) NULL COMMENT 'Last 4 digits of PAN',
    card_expiry_month BIGINT NULL COMMENT 'Card expiration month',
    card_expiry_year BIGINT NULL COMMENT 'Card expiration year',
    cardholder_name VARCHAR(255) NULL COMMENT 'Name on card',
    transaction_type VARCHAR(255) NOT NULL COMMENT 'Transaction type code',
    entry_mode VARCHAR(255) NOT NULL COMMENT 'How card was presented',
    amount NUMERIC(18,2) NOT NULL COMMENT 'Transaction amount',
    currency_code VARCHAR(255) NOT NULL COMMENT 'ISO 4217 currency code',
    billing_amount NUMERIC(18,2) NULL COMMENT 'Amount in cardholder billing currency',
    billing_currency VARCHAR(255) NULL COMMENT 'Billing currency code',
    cashback_amount NUMERIC(18,2) NULL COMMENT 'Cashback amount (debit POS)',
    surcharge_amount NUMERIC(18,2) NULL COMMENT 'Surcharge/convenience fee',
    merchant_name VARCHAR(255) NULL COMMENT 'Merchant name',
    merchant_id VARCHAR(255) NULL COMMENT 'Merchant identifier',
    merchant_category_code VARCHAR(255) NULL COMMENT 'MCC (4-digit)',
    terminal_id VARCHAR(255) NULL COMMENT 'Terminal identifier',
    merchant_city VARCHAR(255) NULL COMMENT 'Merchant city',
    merchant_state VARCHAR(255) NULL COMMENT 'Merchant state/province',
    merchant_country VARCHAR(255) NULL COMMENT 'Merchant country code',
    pos_condition_code VARCHAR(255) NULL COMMENT 'POS condition code',
    network_response_code VARCHAR(255) NULL COMMENT 'Network response/action code',
    avs_response_code VARCHAR(255) NULL COMMENT 'Address verification response',
    cvv_response_code VARCHAR(255) NULL COMMENT 'CVV verification response',
    is_pin_present BOOLEAN NULL COMMENT 'Whether PIN was used',
    is_recurring BOOLEAN NULL COMMENT 'Recurring/subscription indicator',
    is_card_present BOOLEAN NULL COMMENT 'Card-present vs card-not-present',
    digital_wallet_type VARCHAR(255) NULL COMMENT 'Digital wallet if applicable',
    dispute_status VARCHAR(255) NULL COMMENT 'Chargeback/dispute status',
    dispute_reason_code VARCHAR(255) NULL COMMENT 'Dispute/chargeback reason code',
    interchange_fee NUMERIC(12,4) NULL COMMENT 'Interchange fee amount',
    network_fee NUMERIC(12,4) NULL COMMENT 'Network/assessment fee',
    status VARCHAR(255) NOT NULL COMMENT 'Transaction lifecycle status',
    auth_timestamp TIMESTAMP NULL COMMENT 'Authorization timestamp',
    settlement_timestamp TIMESTAMP NULL COMMENT 'Settlement timestamp',
    posted_timestamp TIMESTAMP NULL COMMENT 'Posted to account timestamp',
    source_product VARCHAR(255) NOT NULL COMMENT 'JH product: CPS, TAP2LOCAL, IPAY_CARDPAY, EPS_GATEWAY',
    channel VARCHAR(255) NULL COMMENT 'Channel',
    _cdc_sequence_id VARCHAR(255) NOT NULL COMMENT 'CDC sequence number for ordering',
    _cdc_operation VARCHAR(255) NOT NULL COMMENT 'CDC operation type: I(nsert), U(pdate), D(elete)',
    _cdc_timestamp TIMESTAMP NOT NULL COMMENT 'Timestamp when change was captured at source',
    _cdc_source_system VARCHAR(255) NOT NULL COMMENT 'Source application identifier',
    _cdc_load_timestamp TIMESTAMP NOT NULL COMMENT 'Timestamp when record landed in BigQuery raw zone',
    _tenant_id VARCHAR(255) NOT NULL COMMENT 'Financial institution identifier for multi-tenant isolation'
,
    PRIMARY KEY (card_transaction_id)
);

COMMENT ON TABLE raw_card IS 'Raw Card transaction data from source systems';
